name: Secrets

on:
  push:
    branches: [ "master" ]
    paths:
      - '**.md'
  pull_request:
    branches: [ "master" ]
    paths:
      - '**.md'
  workflow_dispatch:

jobs:
  secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - name: Install Wrangler
        run: npm install wrangler
      - name: Update Secrets
        run: |
          echo ${{secrets.W_API_KEY}}      | npx wrangler secret put W_API_KEY
          echo ${{secrets.META_VERIFY}}    | npx wrangler secret put META_VERIFY
          echo ${{secrets.CELL_DEMO}}      | npx wrangler secret put CELL_DEMO
          echo ${{secrets.CELL_FACEBOOK}}  | npx wrangler secret put CELL_FACEBOOK
          echo ${{secrets.IDEIAS_CASA}}    | npx wrangler secret put IDEIAS_CASA
          echo ${{secrets.OPENAI_API_KEY}} | npx wrangler secret put OPENAI_API_KEY
          echo ${{secrets.AWS_KEY_ACC}} | npx wrangler secret put OPENAI_API_KEY
          echo ${{secrets.AWS_KEY_ID}} | npx wrangler secret put OPENAI_API_KEY
          echo ${{secrets.AWS_REGION}} | npx wrangler secret put OPENAI_API_KEY
        env:
          CLOUDFLARE_API_TOKEN: ${{secrets.ALLWK}}
